version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mediaPlatform
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis